### ISSUE TITLE
Failed to load module script: Expected a JavaScript module .. MIME type of ""

### ISSUE THREAD

**Issue by opicron** [colorful-tones/acf-slider-block#2]
When testing this plugin I see the following console error in the browser:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.`

Am I missing some step to get this working?

**Comment by opicron** [comment]
My bad I found the issue and solution!

**Comment by colorful-tones** [comment]
Yes, it is a MIME-type issue with Local likely. [Reported with a workaround here](https://github.com/colorful-tones/acf-slider-block/issues/1), but please verify if you don't mind @opicron.

**Comment by opicron** [comment]
Correct, I had to adjust the .htaccess file as such to solve this:

I am hosting my websites on Cloudways for anybody who needs to know :).

```
<IfModule mod_mime.c>
  AddType text/javascript js mjs
</IfModule>
```
